name: Call Supabase Edge Function

# DÃ©clenchement toutes les 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # permet de lancer manuellement depuis GitHub

jobs:
  call-edge:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          echo "Calling Supabase Edge Function..."
          curl -X POST https://emgxngtzflmvqsetwugt.functions.supabase.co/check_confirm_mail
