name: Call Supabase Edge Function

# DÃ©clenchement toutes les 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # permet de lancer manuellement depuis GitHub

jobs:
  call-edge:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          echo "Calling Supabase Edge Function..."
          curl -L -X POST 'https://emgxngtzflmvqsetwugt.supabase.co/functions/v1/check_confirm_mail' \
            -H 'Authorization: Bearer sb_publishable_9zr8Ozvb2fbTUtbXndUVlQ_yyf_WAWG' \
            -H 'apikey: sb_publishable_9zr8Ozvb2fbTUtbXndUVlQ_yyf_WAWG' \
            -H 'Content-Type: application/json' \
              --data '{"name":"Functions"}'
